### ISSUE TITLE
setup 에서 cv2 설치 오류가 발생합니다.

### ISSUE THREAD

**Issue by zzangfan** [Korea-Health-Datathon/KHD2020#78]
2020-09-22 07:13:21.325426: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
User session exited

**Comment by sungchul2** [comment]
`nsml_package.txt` 에 `libgl1-mesa-glx` 를 추가해주세요

**Comment by gibiee** [comment]
setup.py의 install_requires 리스트에 `opencv-python`가 아니라 `opencv-python-headless`으로 추가해보시길 바랍니다.
